# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    prefix-development: ci
    include: scope

# Separated roots are subject to be replaced with the single '/'-root directory as soon as 
# https://github.com/dependabot/dependabot-core/issues/4364 issue is fixed 
- package-ecosystem: maven
  directory: /org.eclipse.lsp4e
  schedule:
    interval: daily
  commit-message:
    prefix: fix
    prefix-development: build
    include: scope
  labels:
    - dependencies

- package-ecosystem: maven
  directory: /org.eclipse.lsp4e.test
  schedule:
    interval: daily
  commit-message:
    prefix: fix
    prefix-development: build
    include: scope
  labels:
    - dependencies

- package-ecosystem: maven
  directory: /repository
  schedule:
    interval: daily
  commit-message:
    prefix: fix
    prefix-development: build
    include: scope
  labels:
    - dependencies
